Repository rpgrca/proyecto-ispc-fullstack, pull requests merged in 2022-10, with the labels that each got.

#55 crear index.html y directorio sitio
  sitio/index.html
Labels: enhancement

#57 crear archivo contacto vacio
  sitio/contacto.html
Labels: enhancement, good first issue

#94 primera version de seccion compras
  sitio/compras.html
  sitio/images/no-image.svg
Labels: enhancement

#97 Llenar el archivo vacío con el html requerido
  sitio/contacto.html
Labels: enhancement

#98 un poco de estilo en css
  sitio/compras.html
  sitio/estilos.css
Labels: enhancement

#102 usar bootstrap en lista
  sitio/compras.html
Labels: enhancement

#103 crear consignaciones basado en compras
  sitio/consignaciones.html
Labels: enhancement

#105 Agrego pagina contacto para visitantes no logueados contacto.html
  sitio/contacto2.html
Labels: enhancement

#111 move bs to own dir, adjust stylesheets in htmls
  sitio/bs/css/bootstrap-grid.css
  sitio/bs/css/bootstrap-grid.css.map
  sitio/bs/css/bootstrap-grid.min.css
  sitio/bs/css/bootstrap-grid.min.css.map
  sitio/bs/css/bootstrap-grid.rtl.css
  sitio/bs/css/bootstrap-grid.rtl.css.map
  sitio/bs/css/bootstrap-grid.rtl.min.css
  sitio/bs/css/bootstrap-grid.rtl.min.css.map
  sitio/bs/css/bootstrap-reboot.css
  sitio/bs/css/bootstrap-reboot.css.map
  sitio/bs/css/bootstrap-reboot.min.css
  sitio/bs/css/bootstrap-reboot.min.css.map
  sitio/bs/css/bootstrap-reboot.rtl.css
  sitio/bs/css/bootstrap-reboot.rtl.css.map
  sitio/bs/css/bootstrap-reboot.rtl.min.css
  sitio/bs/css/bootstrap-reboot.rtl.min.css.map
  sitio/bs/css/bootstrap-utilities.css
  sitio/bs/css/bootstrap-utilities.css.map
  sitio/bs/css/bootstrap-utilities.min.css
  sitio/bs/css/bootstrap-utilities.min.css.map
  sitio/bs/css/bootstrap-utilities.rtl.css
  sitio/bs/css/bootstrap-utilities.rtl.css.map
  sitio/bs/css/bootstrap-utilities.rtl.min.css
  sitio/bs/css/bootstrap-utilities.rtl.min.css.map
  sitio/bs/css/bootstrap.css
  sitio/bs/css/bootstrap.css.map
  sitio/bs/css/bootstrap.min.css
  sitio/bs/css/bootstrap.min.css.map
  sitio/bs/css/bootstrap.rtl.css
  sitio/bs/css/bootstrap.rtl.css.map
  sitio/bs/css/bootstrap.rtl.min.css
  sitio/bs/css/bootstrap.rtl.min.css.map
  sitio/bs/js/bootstrap.bundle.js
  sitio/bs/js/bootstrap.bundle.js.map
  sitio/bs/js/bootstrap.bundle.min.js
  sitio/bs/js/bootstrap.bundle.min.js.map
  sitio/bs/js/bootstrap.esm.js
  sitio/bs/js/bootstrap.esm.js.map
  sitio/bs/js/bootstrap.esm.min.js
  sitio/bs/js/bootstrap.esm.min.js.map
  sitio/bs/js/bootstrap.js
  sitio/bs/js/bootstrap.js.map
  sitio/bs/js/bootstrap.min.js
  sitio/bs/js/bootstrap.min.js.map
  sitio/compras.html
  sitio/consignaciones.html
  sitio/css/estilos.css
  sitio/formulario.html
  sitio/login.html
  sitio/perfil.html
  sitio/reestablecer.html
  sitio/subasta-martillero.html
Labels: enhancement

#119 subo logo del sitio en formato svg
  sitio/images/logo_bidon.svg
Labels: enhancement

#116 subo favicon
  sitio/images/favicon.png
Labels: enhancement

#117 aquí subo el fomulario de registro .html
  sitio/registro.html
Labels: enhancement

#120 agrego estilos en estilos.css
  sitio/css/estilos.css
Labels: enhancement

#129 subo index.html, el logo que va y una imagen para la página central
  sitio/images/bidon_logo.svg
  sitio/images/sillon.jpg
  sitio/index.html
Labels: enhancement

#128 corrijo estilos y enlaces en form registro y login
  sitio/css/estilos.css
  sitio/login.html
  sitio/registro.html
Labels: enhancement

#143 subo estilos de index en los que estuve trabajando, falta continuar
  view/css/estilos.css
  view/index.html
Labels: enhancement

#144 subo modificaciones en index y agrego imagen
  view/images/room.jpg
  view/index.html
Labels: enhancement

#145 108 tk43 anuncio
  view/creacion-subasta.html
Labels: enhancement

#147 subo página de como funciona
  view/funcionamiento.html
Labels: enhancement

#148 Fix registro
  view/acerca.html
  view/catalogo.html
  view/compras.html
  view/consignaciones.html
  view/creacion-articulo.html
  view/creacion-subasta.html
  view/css/estilos.css
  view/images/antiguo-respaldo-cama.jpg
  view/images/escritorio-estilo-ingles.jpg
  view/images/fideera-antigua.jpg
  view/images/juego-sillas-inglesas.jpg
  view/images/ropero-provenzal.jpg
  view/images/vitrina-oriental.jpg
  view/index.html
  view/reestablecer.html
  view/registro.html
Labels: enhancement

#151 149 deployar
  view/acerca.html
  view/catalogo.html
  view/compras.html
  view/consignaciones.html
  view/contacto-visitante.html
  view/contacto.html
  view/creacion-articulo.html
  view/creacion-consignatario.html
  view/creacion-subasta.html
  view/css/contacto2.css
  view/css/estilos.css
  view/funcionamiento.html
  view/index.html
  view/login.html
  view/perfil.html
  view/reestablecer.html
  view/registro.html
  view/subasta-martillero.html
  view/subasta.html
Labels: enhancement

#162 subo script de base de datos
  bidon_subastas.sql
Labels: documentation

#201 Fastapi
  .github/workflows/python.yml
  .gitignore
  controller/login.py
  controller/reestablecer.py
  controller/registro.py
  main.py
  main_tests.py
  model/usuarios.py
  requirements.txt
  tests/login_tests.py
  tests/reestablecer_tests.py
  tests/registro_tests.py
  view/contacto-visitante.html
  view/contacto.html
  view/creacion-articulo.html
  view/creacion-consignatario.html
  view/creacion-subasta.html
  view/js/funciones.js
  view/login.html
  view/perfil.html
  view/reestablecer.html
  view/registro.html
Labels: enhancement

#228 creacion de clase Puja
  model/pujas.py
Labels: enhancement

#233 agrego querie con insert a subastas
  model/queries.sql
Labels: enhancement

#235 creación de la clase Pujas en pujas.py
  model/pujas.py
Labels: enhancement

#234 subo querie para traer informacion de usuario x
  model/queries.sql
Labels: enhancement

#236 creacion de una querie para Lotes
  model/queries.sql
Labels: enhancement

#238 creacion de registro de venta para queries.sql
  model/queries.sql
Labels: enhancement

#239 subo querie de ventas para comprador dado
  model/queries.sql
Labels: enhancement

#243 subo querie para crear una puja
  model/queries.sql
Labels: enhancement

#245 subo querie para traer el último registro de una subasta
  model/queries.sql
Labels: enhancement

#248 Separar servicios
  .github/workflows/python.yml
  controller/consignatario.py
  controller/controlador.py
  controller/login.py
  controller/lote.py
  controller/puja.py
  controller/reestablecer.py
  controller/registro.py
  controller/subasta.py
  controller/usuario.py
  main.py
  main_tests.py
  model/usuarios.py
  services/__init__.py
  services/login.py
  services/lotes.py
  services/pujas.py
  services/servicio.py
  services/subastas.py
  services/usuarios.py
  tests/consignatario_tests.py
  tests/login_tests.py
  tests/lote_tests.py
  tests/puja_tests.py
  tests/pujador_tests.py
  tests/reestablecer_tests.py
  tests/registro_tests.py
  tests/subasta_tests.py
  tests/usuario_tests.py
Labels: enhancement

#249 Tests articulos
  controller/articulo.py
  main_tests.py
  model/articulos.py
  model/content_provider/memory.py
  model/content_provider/mysql.py
  model/usuarios.py
  services/articulos.py
  tests/articulo_tests.py
  tests/constantes.py
Labels: enhancement

#251 Clean up
  controller/controlador.py
  controller/lote.py
  controller/puja.py
  main.py
  model/articulos.py
  model/content_provider/mysql.py
  services/articulos.py
  services/lotes.py
  services/pujas.py
  services/servicio.py
  services/subastas.py
  services/usuarios.py
  tests/articulo_tests.py
  tests/lote_tests.py
  tests/puja_tests.py
Labels: enhancement

#250 subo archivo ventas.py
  model/ventas.py
Labels: enhancement

#252 Agregar controladores de ventas y catalogo
  controller/catalogo.py
  controller/libro_diario.py
  main_tests.py
  model/articulos.py
  model/content_provider/memory.py
  model/content_provider/mysql.py
  model/database.py
  model/lotes.py
  model/pujas.py
  model/usuarios.py
  model/ventas.py
  services/articulos.py
  services/libro_diario.py
  services/lotes.py
  services/pujas.py
  services/usuarios.py
  tests/articulo_tests.py
  tests/catalogo_tests.py
  tests/constantes.py
  tests/lote_tests.py
  tests/puja_tests.py
  tests/subasta_tests.py
  tests/venta_tests.py
Labels: enhancement

#253 Actualizar pipeline
  .coveragerc
  .github/workflows/python.yml
Labels: enhancement

#254 Simplificar
  controller/perfil.py
  controller/usuario.py
  main.py
  main_tests.py
  model/articulos.py
  model/content_provider/memory.py
  model/content_provider/mysql.py
  model/usuarios.py
  services/articulos.py
  services/usuarios.py
  tests/consignatario_tests.py
  tests/constantes.py
  tests/lote_tests.py
  tests/pujador_tests.py
  tests/usuario_tests.py
Labels: enhancement

#256 Simplificar
  controller/consignaciones.py
  controller/contacto.py
  controller/login.py
  controller/reestablecer.py
  controller/registro.py
  controller/usuario.py
  main.py
  main_tests.py
  model/content_provider/memory.py
  model/usuarios.py
  services/email_sender.py
  services/login.py
  services/usuarios.py
  tests/articulo_tests.py
  tests/constantes.py
  tests/email_sender_spy.py
  tests/login_tests.py
  tests/puja_tests.py
  tests/reestablecer_tests.py
  tests/registro_tests.py
  tests/usuario_tests.py
  tests/venta_tests.py
Labels: enhancement
